# Generated by Django 4.2 on 2023-07-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal_players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
